## YAML Template.
---
QuestTask:
  Ticks: 1
WorldClassification:
  name: quest_flat
  generateStructures: false
  generator:
  seed: 42
  type: FLAT
  noInventory: true
  environment: NORMAL
  spawnMonsters: true
  spawnAnimals: true
  difficulty: NORMAL
  gameMode: SURVIVAL
  playerVsPlayer: false
  entitySpawnCheck: true
  naturalEntityTypes: []
  customEntityTypes: [all]