## YAML Template.
name: Quest
main: com.mahn42.anhalter42.quest.QuestPlugin
version: 0.01
commands:
   q_start:
      description: quest starten
      usage: /q_start <questfile|questdirectory>
      permission: q.start
      permission-message: You don't have permission
   q_stop:
      description: quest stoppen
      usage: /q_stop <questname>
      permission: q.stop
      permission-message: You don't have permission
permissions:
    q.*:
        description: Gives access to all quest commands
        children:
            q.start: true
            q.stop: true
    q.start:
        description: Allows you to start a quest from file
        default: false
    q.stop:
        description: Allows you to stop a running quest with given quest name
        default: false
